name: hive
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - immutables
  - numpy
  - networkx
  - pandas
  - pip
  - PyYAML
  - tqdm
  - h3-py=3.6.4
  - scipy
  - pip:
      returns