name: hive
channels:
  - defaults
dependencies:
  - geopandas=0.4
  - ipython=7.4
  - jupyter=1.0
  - jupyterlab=0.35
  - matplotlib=3.0
  - numpy=1.16
  - pandas=0.24
  - pip=19.0
  - python=3.6
  - pytz=2018.9
  - scikit-learn=0.21
  - scipy=1.2
  - pip:
    - utm==0.5
    - haversine==2.0