name: hive
channels:
  - defaults
dependencies:
  - geopandas=0.4
  - h3=3.4.3
  - numpy=1.16
  - pandas=0.24
  - pip=19.0
  - python=3.7
  - pytz=2018.9
  - pip:
    - utm==0.5
    - requests==2.21
    - haversine==2.0
    - PyYAML==5.1