---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "[%(levelname)s] %(asctime)s - %(message)s"
  csv:
    format: "%(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: outputs/run.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: outputs/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
 vehicle_log:
   level: INFO

 base_log:
   level: INFO

 station_log:
   level: INFO

 dispatcher_log:
   level: INFO

 run_log:
   level: INFO
   handlers: [console, info_file_handler, error_file_handler]

# root:
#   level: INFO
#   handlers: [console, info_file_handler, error_file_handler]
