METERS_TO_MILES = 0.000621371

HOURS_TO_SECONDS = 3600
SECONDS_TO_HOURS = HOURS_TO_SECONDS ** -1

HOURS_TO_MINUTES = 60
MINUTES_TO_HOURS = HOURS_TO_MINUTES ** -1

MINUTES_TO_SECONDS = 60
SECONDS_TO_MINUTES = MINUTES_TO_SECONDS ** -1
