output_base_directory: ""
log_run: True
log_states: True
log_events: True
log_stats: True
log_level: INFO
log_sim_config:
- 'instruction'
- 'station_state'
- 'vehicle_state'
- 'add_request_event'
- 'cancel_request_event'
- 'pickup_request_event'
- 'dropoff_request_event'
- 'vehicle_charge_event'
- 'vehicle_move_event'
- 'station_load_event'
- 'refuel_search_event'
- 'driver_schedule_event'
log_station_capacities: True
local_parallelism: 1
local_parallelism_timeout_sec: 60
lazy_file_reading: False
wkt_x_y_ordering: True