output_base_directory: ""
log_run: True
log_sim: True
log_level: INFO
log_sim_config:
- 'add_request'
- 'cancel_request'
- 'pickup_request'
- 'instruction'
- 'vehicle_charge_event'
- 'vehicle_move_event'
log_period_seconds: 60
local_parallelism: 1
local_parallelism_timeout_sec: 60
lazy_file_reading: False
track_stats: True