from hive.dispatcher.forecaster.forecaster_interface import ForecasterInterface
from hive.dispatcher.forecaster.forecast import Forecast, ForecastType
from hive.dispatcher.forecaster.basic_forecaster import BasicForecaster