name: tests 

on:
  push:
      branches: [ main ]
  pull_request:

jobs:
  test:
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
          python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

      env:
        PYTHON: ${{ matrix.python-version }}

      steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
