name: tests 

on:
  push:
      branches: [ main ]
  pull_request:

jobs:
  test:
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
          python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

      env:
        PYTHON: ${{ matrix.python-version }}

      steps:
      - uses: actions/checkout@v3

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package 
        run: |
          pip install ".[dev]" 

      - name: Run mypy
        run: mypy . --ignore-missing-imports 

      - name: Run black
        run: |
          black nrel tests --check

      - name: Python unit tests 
        run: |
          pytest tests/ -v 
      
      - name: HIVE Denver Demo test
        run: |
          hive denver_demo.yaml
