name: tests 

on:
  push:
      branches: [ main ]
  pull_request:

jobs:
  test:
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
          python-version: ['3.7', '3.8', '3.9', '3.10']

      env:
        PYTHON: ${{ matrix.python-version }}

      steps:
      - uses: actions/checkout@v2

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run black
        run: black nrel tests --check

      - name: Python unit tests 
        run: |
          pip install pytest
          pip install . 
          pytest tests/ -v 
      
      - name: HIVE Denver Demo test
        run: |
          pip install -e .
          hive denver_demo.yaml
